name: workflow-test-3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: step A1 (Error)
        continue-on-error: false
        shell: bash
        run: |
          eeecho "Job A - Step A1"
          
  jobB:
    runs-on: ubuntu-latest
    steps:
      - name: step B1
        shell: bash
        run: |
          echo "Job B - Step B1"
          
      - name: step B2
        shell: bash
        run: |
          echo "Job B - Step B2"