name: workflow-test-7

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: step A1 (Error)
        shell: bash
        run: |
          echo "Job A - Step A1"
          
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - name: step B1
        shell: bash
        run: |
          echo "Job B - Step B1 - need jobA" 
          
  jobC:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - name: step C1
        shell: bash
        run: |
          echo "Job C - Step C1 - need jobA"
          
  jobD:
    runs-on: ubuntu-latest
    needs: jobB
    steps:
      - name: step D1
        shell: bash
        run: |
          echo "Job D - Step D1 - need jobB"

  jobE:
    runs-on: ubuntu-latest
    needs: jobD
    steps:
      - name: step E1
        shell: bash
        run: |
          echo "Job E - Step E1 - need jobD"
          
  jobF:
    runs-on: ubuntu-latest
    needs: [jobC, jobE]
    steps:
      - name: step F1
        shell: bash
        run: |
          echo "Job F - Step F1 - needs [jobC, jobE]"